---
title: "homework"
output: html_document
date: "2022-10-06"
---

## load library

```{r}
library(sf)
library(tidyverse) 
```

## Data loading

```{r}

shape <- st_read("data/statsnzterritorial-authority-2018-generalised-SHP/territorial-authority-2018-generalised.shp")

# dTolerance is the distance in which any “wiggles” will be straightened
shape_simple <- st_simplify(shape, dTolerance = 1000)

employed_2018 <- read_csv("data/stats_edited.csv")


# added test to last row to make character for example
Datatypelist <- shape_simple %>% 
  summarise_all(class)
Datatypelist


# Datatypelist2 <- employed_2018_2 %>% 
#   summarise_all(class)
# Datatypelist

summary(shape_simple)

shape_simple %>%
  st_geometry()%>%
  plot()
```

## Data manipulation

join on the description

```{r}
# join on the description 

shape2 <- shape_simple%>%
  merge(.,
        employed_2018,
        by.x="TA2018_V_1", 
        by.y="Area_Description")
```

Join on the ID by making the column numeric

```{r}


shape3 <- shape_simple %>%
  mutate(TA2018_V1_=(as.numeric(TA2018_V1_)))%>%
  merge(.,
        employed_2018,
        by.x="TA2018_V1_", 
        by.y="Area_Code")

#or 

# shape3 <- shape %>%
#   transform(., TA2018_V1_ = as.numeric(TA2018_V1_))%>%
#   merge(.,
#         employed_2018,
#         by.x="TA2018_V1_", 
#         by.y="Area_Code")

# or also 
#shape$TA2018_V1_ = as.numeric(shape$TA2018_V1_)
```

## Data mapping

```{r}
library(tmap)
tmap_mode("plot")
# change the fill to your column name if different
my_map<-shape2 %>%
  qtm(.,fill = "Paid employee")

my_map
```
